### PR TITLE
IR. Next release support

### PR DESCRIPTION
**Pull request by turansky**
Related issues:
https://github.com/JetBrains/kotlin/pull/4017
https://github.com/Kotlin/dukat/pull/430

### CODE REVIEW

**Comment by fluidsonic** [comment]
@turansky is there a way for me to test the compiler changes with my library and project?

**Comment by turansky** [comment]
> is there a way for me to test the compiler changes with my library and project?

Kotlin from `master` branch can be used :)
AFAIK public dev builds are unavailable now

PR must have "zero effect" now, but will be requirement for `external interfaces` with `companion object` in future.
Kotlin `1.5.20` marked as target version for [KT-40235](https://youtrack.jetbrains.com/issue/KT-40235), but I suggest earlier version.

**Comment by fluidsonic** [comment]
What's the benefit of `@JsName("null")` on an `external interface`?
A name of an `external interface` will never end up in JS code anyway, so it won't make any difference.

**Comment by turansky** [comment]
`NodeFilter` - external interface

[Test exapmle](https://pl.kotl.in/6SMaaQd1Y)
[Issue](https://youtrack.jetbrains.com/issue/KT-44394)

**Pull request closed without merging**
